# Site Config for production Jekyll build
# A plugin loads development variables of _config_development.yml

title: "micro:bit Playground"
description: "micro:bit playground"
destination: _site

url:  https://microbit-playground.co.uk
subscribe_rss: /atom.xml
baseurl:

# default images
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title
kramdown:
  toc_levels: 1..2

highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-gist
  - github-pages

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: page
titlecase: true
limit_posts: 0

# Site owner
owner:
  name: Jez Dean
  web: http://geekteacher.co.uk
  email: jezdean@gmail.com
  twitter: JezMr
  bio: "Teacher from the UK exploring technology and education."
  avatar: author-jez-dean.jpg # 160x160 px image for author byline
  disqus-shortname: pythonplayground
  google:
    plus:
    ad-client:
    ad-slot:

google-tracking-code: UA-74549615-2

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", ".masters", "backups", "*.py", ".pyc"]
